name: Claude Code (YOLO Mode)

on:
  issue_comment:
    types: [created]

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    # YOLO: Force the PAT as an environment variable for the whole job.
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
      # YOLO: Checkout using the PAT. This authenticates git for all subsequent steps.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      # YOLO: Run the action, explicitly passing the PAT again just in case.
      - name: Run Claude Code
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          trigger_phrase: "@claude"
